apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: my-test3-qwtb
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: my-test3-qwtb
    app.kubernetes.io/part-of: my-test3-1
  name: my-test3-qwtb
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app.kubernetes.io/instance: my-test3-qwtb
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: my-test3-qwtb
    spec:
      containers:
      - image: quay.io/redhat-user-workloads-stage/mkosiarc-tenant/my-test3-1/my-test3-qwtb@sha256:5ea452bb093185651015a6e83f7ae1da5cbb95be6050b1e4ca29304ed5cf685d
        imagePullPolicy: Always
        name: container-image
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 10m
            memory: 256Mi
status: {}
